site_name: worker documentation
site_description: worker is intended to easily submit and manage embarrasignly parallel computations for, e.g., parameter exploration
site_author: Geert Jan Bex
pages:
- ['index.md', 'Introduction and motivation']
- ['contact.md', 'Contact information']
site_dir: html_docs/worker
theme: readthedocs
